/-
Copyright (c) 2024-2025 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Katerina Hristova
-/

import Mathlib.Algebra.Polynomial.Basic
import Mathlib.Algebra.Polynomial.Bivariate
import Mathlib.Algebra.Polynomial.Basic
import Mathlib.Algebra.Polynomial.Eval.Irreducible
import Mathlib.FieldTheory.RatFunc.Basic
import Mathlib.RingTheory.Ideal.Span


/-!
  # Preliminary Definitions and Theorems on polynomials and rings of rational functions.
-/

open Polynomial
open Polynomial.Bivariate

namespace Ideal
section

/-- A principal ideal is an ideal generated by a single element. -/
def principalIdeal {F : Type} [Semiring F] (f : F) : Ideal F := Ideal.span {f}

/-- A principal ideal in a polynomial ring is maximal if and only if its generator is
an irreducble polynomial. -/
lemma principal_is_maximal_iff_irred {F : Type} [CommRing F] (f : F[X]) :
  (principalIdeal f).IsMaximal ↔ Irreducible f := by sorry

end
end Ideal

namespace ToRatFunc
section

/-- The algebra map embedding the univariate polynomial ring into its ring of rational functions. -/
noncomputable def univPolyHom {F : Type} [CommRing F] [IsDomain F] : F[X] →+* RatFunc F :=
  algebraMap (F[X]) (RatFunc F)


/-- The algebra map embedding the bivariate polynomial ring into its ring of rational functions. -/
noncomputable def bivPolyHom {F : Type} [CommRing F] [IsDomain F] :
  Polynomial (F[X]) →+* Polynomial (RatFunc F) := Polynomial.mapRingHom (univPolyHom)


end
end ToRatFunc
